version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgis/postgis:latest # postgis is postgres with installed extension PostGIS
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=AnimalChipping
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U user -d AnimalChipping'" ]
      interval: 10s
      timeout: 3s
      retries: 3
  
  
  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: mihailuse/animal_chipping:latest
    ports:
      - "80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;Database=AnimalChipping;User Id=user;Password=password
  
  
  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase2
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: 2
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1, 2 или 3 - запуск тестов для соответствующего этапа