version: '3.9'

services:
  # Сервис для разворачивания контейнера с базой данных
  database:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=AnimalChipping
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  
  
  # Сервис для разворачивания контейнера с приложением
  webapi:
    image: mihailuse/animal_chipping:latest
    ports:
      - "80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=database;Port=5432;Database=AnimalChipping;User Id=user;Password=password
  
  
  # Сервис для разворачивания контейнера с автотестами
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: all
      # all - запуск всех тестов из трёх доступных этапов
      # 0, 1 или 2 - запуск тестов для соответствующего этапа